"use client";

import { useQuery } from "@tanstack/react-query";
import * as Accordion from "@radix-ui/react-accordion";
import * as Tooltip from "@radix-ui/react-tooltip";
import { ChevronDown, Info } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Spinner } from "@/components/ui/Spinner";
import { fetchLlmDecisions } from "@/lib/api";

export function AIDecisionLog() {
  const query = useQuery({
    queryKey: ["llm-decisions"],
    queryFn: () => fetchLlmDecisions(5),
    refetchInterval: 60000,
  });

  const decisions = query.data?.data ?? [];

  return (
    <Card>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold text-white">AI Decision Log</h2>
        <Tooltip.Provider>
          <Tooltip.Root>
            <Tooltip.Trigger asChild>
              <span className="cursor-help">
                <Badge variant="accent" className="gap-1">
                  <span>AI-Powered by Gemini 1.5 Pro</span>
                  <Info size={12} />
                </Badge>
              </span>
            </Tooltip.Trigger>
            <Tooltip.Portal>
              <Tooltip.Content
                className="bg-card border border-gray-600 rounded-lg px-3 py-2 text-sm text-gray-300 max-w-xs"
                sideOffset={5}
              >
                Allocation decisions are generated by Google Gemini 1.5 Pro and validated
                against on-chain governance policy before execution.
              </Tooltip.Content>
            </Tooltip.Portal>
          </Tooltip.Root>
        </Tooltip.Provider>
      </div>

      {query.isLoading ? (
        <div className="flex justify-center py-8">
          <Spinner />
        </div>
      ) : decisions.length === 0 ? (
        <p className="text-gray-400 text-center py-8">No decisions recorded yet</p>
      ) : (
        <Accordion.Root type="single" collapsible className="space-y-2">
          {decisions.map((d: any) => (
            <Accordion.Item
              key={d.id}
              value={String(d.id)}
              className="border border-gray-700 rounded-lg overflow-hidden"
            >
              <Accordion.Trigger className="w-full flex items-center justify-between px-4 py-3 bg-surface hover:bg-gray-800 transition-colors">
                <div className="flex items-center gap-3 text-left">
                  <div>
                    <p className="text-sm font-medium text-white">
                      {new Date(d.timestamp).toLocaleString()}
                    </p>
                    <p className="text-xs text-gray-400">
                      ${d.totalValueUsd?.toLocaleString()} · {d.allocations?.length ?? 0} protocols
                    </p>
                  </div>
                </div>
                <ChevronDown
                  size={16}
                  className="text-gray-400 transition-transform data-[state=open]:rotate-180"
                />
              </Accordion.Trigger>
              <Accordion.Content className="px-4 pb-4 bg-surface">
                {/* Allocation table */}
                <table className="w-full text-xs mt-3 mb-3">
                  <thead>
                    <tr className="text-gray-500 border-b border-gray-700">
                      <th className="text-left pb-2">Protocol</th>
                      <th className="text-right pb-2">Allocation</th>
                      <th className="text-right pb-2">APY</th>
                      <th className="text-right pb-2">Risk</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-700">
                    {(d.allocations ?? []).map((a: any) => (
                      <tr key={a.protocolName}>
                        <td className="py-1.5 text-gray-300">{a.protocolName}</td>
                        <td className="py-1.5 text-right text-white">
                          {((a.basisPoints / 100)).toFixed(1)}%
                        </td>
                        <td className="py-1.5 text-right text-success">{a.apy?.toFixed(2)}%</td>
                        <td className="py-1.5 text-right text-gray-400">{a.riskScore}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>

                {/* LLM Rationale */}
                <div className="bg-card rounded-lg p-3 mt-2">
                  <p className="text-xs text-gray-500 mb-1">LLM Rationale</p>
                  <p className="text-sm text-gray-300 leading-relaxed">{d.llmRationale}</p>
                </div>

                {/* Tx link */}
                {d.txHash && (
                  <a
                    href={`https://sepolia.etherscan.io/tx/${d.txHash}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-accent hover:underline mt-2 block"
                  >
                    View on Etherscan →
                  </a>
                )}
              </Accordion.Content>
            </Accordion.Item>
          ))}
        </Accordion.Root>
      )}
    </Card>
  );
}
